import Image from "next/image";
import logo from "../../../public/images/logo.webp";
import Link from "next/link";

export const TermsAndConditionsComponent = () => {
  return (
    <main className="bg-auth_bg bg-no-repeat bg-fixed min-h-screen w-full overflow-auto">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-10">
        <div className="bg-white rounded-lg shadow-lg px-6 py-8 sm:px-10 sm:py-12">
          <div className="flex justify-center mb-8">
            <Link href="/">
              <div className="flex items-center justify-center space-x-3">
                <Image
                  className="h-10 w-10"
                  priority
                  src={logo}
                  height={40}
                  width={40}
                  alt="Payment Gateway Logo"
                />
                <p className="text-black font-bold text-2xl sm:text-3xl">
                  Payment Gateway
                </p>
              </div>
            </Link>
          </div>

          <h1 className="text-center text-4xl sm:text-5xl font-bold text-gray-900 mb-10 pb-6 border-b border-gray-200">
            Terms & Conditions
          </h1>

          <div className="prose prose-lg max-w-none text-gray-700 space-y-8">
            <p className="text-lg leading-7">
              Welcome to Payment Gateway. These Terms and Conditions govern your
              use of our website and services, including our SaaS platform for
              content management, accounting, invoicing, and HR management.
            </p>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-gray-900">
                1. Acceptance of Terms
              </h2>
              <p>
                By accessing or using our website and services, you agree to be
                bound by these Terms. If you do not agree, you may not access or
                use the services.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-gray-900">
                2. Services Provided
              </h2>
              <p>Payment Gateway offers cloud-based tools including:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>Content Management System (CMS)</li>
                <li>Accounting & Bookkeeping</li>
                <li>Invoicing & Billing</li>
                <li>HR Management (Lite)</li>
              </ul>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-gray-900">
                3. User Accounts
              </h2>
              <p>
                You must register and maintain a user account to access the full
                suite of services. You agree to provide accurate and up-to-date
                information and to maintain the confidentiality of your login
                credentials.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-gray-900">
                4. Subscription and Billing
              </h2>
              <p>
                Our services are provided on a subscription basis. By
                subscribing, you agree to pay the applicable fees, which are
                non-refundable unless stated otherwise. We reserve the right to
                change our pricing with notice.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-gray-900">
                5. Data Ownership
              </h2>
              <p>
                All data inputted by you or generated by your use of the
                services remains your property. Payment Gateway does not claim
                ownership but reserves the right to use anonymized data for
                performance and security enhancements.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-gray-900">
                6. Acceptable Use
              </h2>
              <p>
                You agree not to use the platform for any unlawful, fraudulent,
                or malicious purposes. Violation may result in suspension or
                termination of your account.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-gray-900">
                7. Intellectual Property
              </h2>
              <p>
                All software, content, trademarks, and designs provided by Copa
                Business are the property of the company and protected by
                intellectual property laws. You may not reverse engineer, copy,
                or redistribute our platform.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-gray-900">
                8. Termination
              </h2>
              <p>
                We reserve the right to terminate or suspend access if you
                breach these terms. Upon termination, your access to data may be
                limited unless otherwise agreed.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-gray-900">
                9. Disclaimer
              </h2>
              <p>
                The services are provided &quot;as is&quot; without warranties
                of any kind. We do not guarantee that the software will be
                error-free or uninterrupted.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-gray-900">
                10. Limitation of Liability
              </h2>
              <p>
                Payment Gateway will not be liable for indirect, incidental, or
                consequential damages arising from your use of the services.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-gray-900">
                11. Changes to Terms
              </h2>
              <p>
                We may update these Terms from time to time. Continued use of
                the platform after changes means you accept the revised terms.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-gray-900">
                12. Governing Law
              </h2>
              <p>
                These Terms are governed by the laws of International, and any
                disputes shall be handled in the courts of International Law.
              </p>
            </section>
          </div>
        </div>
      </div>
    </main>
  );
};
